# Generated by Django 6.0.5 on 2026-05-13 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_followers_delete_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='story_images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
